# Copyright (c) 2019, SCALE Lab, Brown University
# All rights reserved.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. 

# ======================================================================
# This file holds parameters for running a DRiLLS agent for training and
# inference. It sets up the RL environment along with the logic synthesis
# environment to train the RL agent. 

# change this to the abc binary path if the command is not recognized system-wide
abc_binary: yosys-abc
yosys_binary: yosys

# path of the design file in one of the accepted formats by ABC
design_name: multiplier
design_file: design/multiplier.v

# the directory to hold the playground an agent uses to practice
playground_dir: playground/multiplier

# standard cell library mapping
mapping:
  clock_period: 2000   # in pico seconds
  library_file: lib/7nm.lib

# FPGA mapping - exlusive with the above
fpga_mapping:
  levels: 100
  lut_inputs: 6

# add more optimization to the toolbox
optimizations:
  - rewrite
  - rewrite -z
  - refactor
  - refactor -z
  - resub
  - resub -z
  - balance

# agent training parameters
episodes: 100
iterations: 25
model_dir: /tmp/brain/model.ckpt   # must be absolute path

# Early stopping
early_stopping: 1
patience: 10
